name: Github Pages CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install and Build ğŸ”§
        run: |
          npm ci
          npm run build

      - name: Deploy with rebase to gh-pages branch ğŸš€
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Clone repo on a temp folder
          git clone --depth=1 --branch=gh-pages https://x-access-token:${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}@github.com/${{ secrets.CI_REPOSITORY_NAME }} gh-pages-temp

          cd gh-pages-temp

          # Adds the destination repository as an explicit remote (redundant but safe)
          git remote add upstream https://x-access-token:${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}@github.com/${{ secrets.CI_REPOSITORY_NAME }}
          git fetch upstream main

          # Rebase with the main branch of target repository
          git rebase upstream/main || echo "âš ï¸ Rebase teve conflitos e foi ignorado"

          # Remove current folder on github.io and copy new dist files into it
          rm -rf portfolio
          mkdir -p portfolio
          cp -r ../dist/* portfolio/

          # Commit and push
          git add .
          git commit -m "Deploy via GitHub Actions ğŸš€" || echo "Nothing to commit"
          git push origin gh-pages --force
